// <auto-generated />
using System;
using ArknightsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArknightsApp.Migrations
{
    [DbContext(typeof(ArknightsDbContext))]
    partial class ArknightsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ArknightsApp.Models.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("ArknightsApp.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ArknightsApp.Models.ModuleLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatBonuses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleLevels");
                });

            modelBuilder.Entity("ArknightsApp.Models.ModuleTalentUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuleLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TalentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpgradeDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpgradeParameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleLevelId");

                    b.HasIndex("TalentId");

                    b.ToTable("ModuleTalentUpgrades");
                });

            modelBuilder.Entity("ArknightsApp.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CnReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FactionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GlobalReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubClassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("OperatorClassId");

                    b.HasIndex("SubClassId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("ArknightsApp.Models.OperatorClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OperatorClasses");
                });

            modelBuilder.Entity("ArknightsApp.Models.OperatorGrowthTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AttackSpeed")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttackType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BlockCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeploymentCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E0BaseAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E0BaseDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E0BaseHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E0BaseResistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E0MaxAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E0MaxDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E0MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E0MaxResistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E1BaseAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E1BaseDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E1BaseHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E1BaseResistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E1MaxAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E1MaxDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E1MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E1MaxResistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E2BaseAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E2BaseDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E2BaseHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E2BaseResistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E2MaxAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E2MaxDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E2MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("E2MaxResistance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedeployTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrustBonusAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrustBonusDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrustBonusHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrustBonusResistance")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId")
                        .IsUnique();

                    b.ToTable("OperatorGrowthTemplates");
                });

            modelBuilder.Entity("ArknightsApp.Models.OperatorModule", b =>
                {
                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("INTEGER");

                    b.HasKey("OperatorId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("OperatorModules");
                });

            modelBuilder.Entity("ArknightsApp.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ArknightsApp.Models.SkillLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpCost")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillLevels");
                });

            modelBuilder.Entity("ArknightsApp.Models.SubClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorClassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperatorClassId");

                    b.ToTable("SubClasses");
                });

            modelBuilder.Entity("ArknightsApp.Models.Talent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("Talents");
                });

            modelBuilder.Entity("ArknightsApp.Models.TalentLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PotentialLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TalentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnlockCondition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TalentId");

                    b.ToTable("TalentLevels");
                });

            modelBuilder.Entity("ArknightsApp.Models.ModuleLevel", b =>
                {
                    b.HasOne("ArknightsApp.Models.Module", "Module")
                        .WithMany("ModuleLevels")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ArknightsApp.Models.ModuleTalentUpgrade", b =>
                {
                    b.HasOne("ArknightsApp.Models.ModuleLevel", "ModuleLevel")
                        .WithMany("TalentUpgrades")
                        .HasForeignKey("ModuleLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArknightsApp.Models.Talent", "Talent")
                        .WithMany()
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleLevel");

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("ArknightsApp.Models.Operator", b =>
                {
                    b.HasOne("ArknightsApp.Models.Faction", "Faction")
                        .WithMany("Operators")
                        .HasForeignKey("FactionId");

                    b.HasOne("ArknightsApp.Models.OperatorClass", "OperatorClass")
                        .WithMany("Operators")
                        .HasForeignKey("OperatorClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArknightsApp.Models.SubClass", "SubClass")
                        .WithMany("Operators")
                        .HasForeignKey("SubClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("OperatorClass");

                    b.Navigation("SubClass");
                });

            modelBuilder.Entity("ArknightsApp.Models.OperatorGrowthTemplate", b =>
                {
                    b.HasOne("ArknightsApp.Models.Operator", "Operator")
                        .WithOne("GrowthTemplate")
                        .HasForeignKey("ArknightsApp.Models.OperatorGrowthTemplate", "OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("ArknightsApp.Models.OperatorModule", b =>
                {
                    b.HasOne("ArknightsApp.Models.Module", "Module")
                        .WithMany("OperatorModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArknightsApp.Models.Operator", "Operator")
                        .WithMany("OperatorModules")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("ArknightsApp.Models.Skill", b =>
                {
                    b.HasOne("ArknightsApp.Models.Operator", "Operator")
                        .WithMany("Skills")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("ArknightsApp.Models.SkillLevel", b =>
                {
                    b.HasOne("ArknightsApp.Models.Skill", "Skill")
                        .WithMany("SkillLevels")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ArknightsApp.Models.SubClass", b =>
                {
                    b.HasOne("ArknightsApp.Models.OperatorClass", "OperatorClass")
                        .WithMany("SubClasses")
                        .HasForeignKey("OperatorClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperatorClass");
                });

            modelBuilder.Entity("ArknightsApp.Models.Talent", b =>
                {
                    b.HasOne("ArknightsApp.Models.Operator", "Operator")
                        .WithMany("Talents")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("ArknightsApp.Models.TalentLevel", b =>
                {
                    b.HasOne("ArknightsApp.Models.Talent", "Talent")
                        .WithMany("TalentLevels")
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("ArknightsApp.Models.Faction", b =>
                {
                    b.Navigation("Operators");
                });

            modelBuilder.Entity("ArknightsApp.Models.Module", b =>
                {
                    b.Navigation("ModuleLevels");

                    b.Navigation("OperatorModules");
                });

            modelBuilder.Entity("ArknightsApp.Models.ModuleLevel", b =>
                {
                    b.Navigation("TalentUpgrades");
                });

            modelBuilder.Entity("ArknightsApp.Models.Operator", b =>
                {
                    b.Navigation("GrowthTemplate");

                    b.Navigation("OperatorModules");

                    b.Navigation("Skills");

                    b.Navigation("Talents");
                });

            modelBuilder.Entity("ArknightsApp.Models.OperatorClass", b =>
                {
                    b.Navigation("Operators");

                    b.Navigation("SubClasses");
                });

            modelBuilder.Entity("ArknightsApp.Models.Skill", b =>
                {
                    b.Navigation("SkillLevels");
                });

            modelBuilder.Entity("ArknightsApp.Models.SubClass", b =>
                {
                    b.Navigation("Operators");
                });

            modelBuilder.Entity("ArknightsApp.Models.Talent", b =>
                {
                    b.Navigation("TalentLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
